<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ArticleArticleCategoryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * ArticleCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleArticleCategoryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return ArticleArticleCategoryAssignment::class ;
	}
}
