<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ArticleCategoryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * ArticleCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCategoryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return ArticleCategoryAssignment::class ;
	}
}
