<?php

namespace AppBundle\Repository;

use AppBundle\Entity\BrandCategoryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * BrandCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandCategoryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return BrandCategoryAssignment::class ;
	}
}
