<?php

namespace AppBundle\Repository;

/**
 * BrandCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandCategoryAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
