<?php

namespace AppBundle\Repository;

/**
 * BranchCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchCategoryAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
