<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MagazineCategoryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * MagazineCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineCategoryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return MagazineCategoryAssignment::class ;
	}
}
