<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MagazineBranchAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * MagazineBranchAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineBranchAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return MagazineBranchAssignment::class ;
	}
}
