<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MenuMenuEntryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * MenuMenuEntryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuMenuEntryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return MenuMenuEntryAssignment::class ;
	}
}
