<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MenuEntryCategoryAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * MenuEntryCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuEntryCategoryAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return MenuEntryCategoryAssignment::class ;
	}
}
