<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MenuEntryBranchAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * MenuEntryBranchAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuEntryBranchAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return MenuEntryBranchAssignment::class ;
	}
}
