<?php

namespace AppBundle\Repository;

use AppBundle\Entity\NewsletterBlockMagazineAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * NewsletterBlockMagazineAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterBlockMagazineAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return NewsletterBlockMagazineAssignment::class ;
	}
}
