<?php

namespace AppBundle\Repository;

use AppBundle\Entity\NewsletterBlockAdvertAssignment;
use AppBundle\Repository\Base\BaseEntityRepository;

/**
 * NewsletterBlockAdvertAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterBlockAdvertAssignmentRepository extends BaseEntityRepository
{
	/**
	 * {@inheritdoc}
	 */
	protected function getEntityType() {
		return NewsletterBlockAdvertAssignment::class ;
	}
}
