<?php

namespace AppBundle\Repository;

/**
 * TermCategoryAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermCategoryAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
