imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: [pl] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  pl #"%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_lifetime: 31104000
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig
        #- bootstrap_3_horizontal_layout.html.twig
        #- "%kernel.root_dir%/Resources/views/form/fields.html.twig"
    globals:
        searchForm: '@AppBundle\Manager\Globals\Manager'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   mysqli
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: annotation
                alias: GedmoTree
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity/MappedSuperclass"
        dql:
            string_functions:
                 group_concat: AppBundle\Query\MySql\GroupConcat
        

stof_doctrine_extensions:
    orm:
        default:
            uploadable: true
            tree: true
            timestampable: true
            sluggable: true
            
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    logging:    false
#    spool:     { type: memory }
#    spool:
#        type: file
#        path: '%kernel.root_dir%/spool'
    stream_options:
      ssl:
        allow_self_signed: true
        verify_peer: false
        
# Friends of Symfony User Configuration    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\Main\User
    registration:
        form:
            type: AppBundle\Form\Registration\UserRegistrationType
    from_email:
        address:        "%mailer_user%"
        sender_name:    Infomarket

# Short term fix for this bug: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048    
services:
    fos_user.doctrine_registry:
        alias: doctrine
        
# Knp Paginator
knp_paginator:
    template:
         pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
         
# CKEditor
fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
                             
# File uploader ElFinder         
fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        ratings:
            editor: form
            visible_mime_types: ['text', 'csv', 'text/csv', 'application/csv']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/categories/ratings
                        upload_allow: ['text', 'csv', 'text/csv', 'application/csv']
                        upload_deny: ['all']
                        upload_max_size: 512K
        newsletter_users:
            editor: form
            visible_mime_types: ['text', 'csv', 'text/csv', 'application/csv']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/newsletter-users/import
                        upload_allow: ['text', 'csv', 'text/csv', 'application/csv']
                        upload_deny: ['all']
                        upload_max_size: 512K
        icon:
            editor: form
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/categories/icons
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 512K
        featured:
            editor: form
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/categories/featured
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
        topProdukt:
            editor: form
            visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/products/top-produkt
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
        magazine:
            editor: form
            visible_mime_types: ['application/pdf']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/magazines/files
                        upload_allow: ['application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 256M
        default:
            editor: ckeditor
            visible_mime_types: ['all']
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['all']
                        upload_max_size: 100M
                        
                        
# Google Analytics
happyr_google_analytics:
    tracking_id: 'UA-83994037-1'
    http_client: 'httplug.client.happyr_analytics'
    http_message_factory: 'httplug.psr17_request_factory.default'

# HTTPlug    
httplug:
    clients:
        happyr_analytics:
            http_methods_client: true
    plugins:
        logger: ~

# Knp Snappy bundle - screenshots                
knp_snappy:
    pdf:
        enabled:    true
        binary:     "%wkhtmltopdf_binary%"
        options:    []
    image:
        enabled:    true
        binary:     "%wkhtmltoimage_binary%"
        options:    []
    temporary_folder: '%kernel.cache_dir%/snappy'

# Google charts    
cmen_google_charts:
    version: "current"

doctrine_migrations:
    # Connection to use for the migrations
    dir_name: '%kernel.project_dir%/src/AppBundle/Migrations'
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
    namespace: App\Migrations


