security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_EDITOR:        ROLE_BENCHMARK, ROLE_USER
        ROLE_PUBLISHER:     ROLE_EDITOR
        ROLE_RATING_EDITOR: ROLE_EDITOR
        ROLE_ADMIN:         ROLE_PUBLISHER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern: ^/admin
            anonymous: true
            form_login:
                provider:       fos_userbundle
                login_path:     admin_login
                check_path:     admin_login_check
                default_target_path: admin
            logout:
                path:           admin_logout
                target:         admin_login
        benchmark:
            pattern: ^/benchmark
            anonymous: true
            form_login:
                provider:       fos_userbundle
                login_path:     benchmark_login
                check_path:     benchmark_login_check
                default_target_path: benchmark
            logout:
                path:           benchmark_logout
                target:         benchmark_login
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            
    access_control:
        # Registration
        - { path: /login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        - { path: /logout$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        - { path: /register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        - { path: /resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        
        # Benchmark site
        - { path: ^/benchmark, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        
        # IP, IM sites
        # - { path: /magazines/open, role: IS_AUTHENTICATED_FULLY, requires_channel: '%secure_scheme%' }
        
        # Admin site
        - { path: ^/admin/settings, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: ^/admin/users, role: ROLE_ADMIN, requires_channel: '%secure_scheme%' }
        
        - { path: ^/admin/newsletter, role: ROLE_ADMIN, requires_channel: '%secure_scheme%' }
        
        - { path: _assignments/delete, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: articles/delete, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: /delete, role: ROLE_ADMIN, requires_channel: '%secure_scheme%' }
        
        - { path: /new, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: /copy, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: /edit, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: /set_published, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: /set_featured, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        
        - { path: ^/admin, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        
        # Uploads
        - { path: ^/efconnect, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        - { path: ^/elfinder, role: ROLE_EDITOR, requires_channel: '%secure_scheme%' }
        
        # Other
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_scheme%' }
        