services:
    AppBundle\Manager\Params\Benchmark\ContextParamsManager:
        arguments:
            - '@AppBundle\Repository\Benchmark\CategoryRepository'
            - '@AppBundle\Repository\Admin\Assignments\UserCategoryAssignmentRepository'
            - '@AppBundle\Repository\Benchmark\BenchmarkMessageRepository'
            - '@AppBundle\Manager\Params\Base\ParamsManager'
            - '@security.token_storage'