AppBundle\Entity\Assignments\AdvertCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [advert, category]
            errorPath: category
            ignoreNull: false
            message: 'advertCategoryAssignment.unique'
                