AppBundle\Entity\Assignments\ProductCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [product, segment, category]
            ignoreNull: false
            message: 'productCategoryAssignment.unique'
                