AppBundle\Entity\Assignments\MagazineCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [magazine, category]
            ignoreNull: false
            message: 'magazineCategoryAssignment.unique'
                