AppBundle\Entity\Assignments\ArticleBrandAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [article, brand]
            errorPath: brand
            ignoreNull: false
            message: 'articleBrandAssignment.unique'
        - Callback: validate