AppBundle\Entity\Assignments\NewsletterBlockArticleAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [newsletterBlock, article]
            errorPath: article
            ignoreNull: false
            message: 'newsletterBlockArticleAssignment.unique'
                