AppBundle\Entity\Assignments\MenuEntryBranchAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [menuEntry, branch]
            ignoreNull: false
            message: 'menuEntryBranchAssignment.unique'
                