AppBundle\Entity\Base\Image:
    properties:
        forcedWidth:
            - Range:
                min: 0
                max: 2000
        forcedHeight:
            - Range:
                min: 0
                max: 2000 