AppBundle\Entity\Main\BenchmarkField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [category, fieldType, valueNumber]
            errorPath: category
            ignoreNull: false
            message: 'benchmarkField.unique'
    properties:
        fieldName:
            - NotBlank: ~
        valueNumber:
            - NotBlank: ~
            - Range:
                min: 1
                max: 30
                