AppBundle\Entity\Main\NewsletterPageTemplate:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        content:
            - NotBlank: ~