AppBundle\Entity\Main\Menu:
    properties:
        name:
            - NotBlank: ~
        menuMenuEntryAssignments:
            - Count:
                groups: [removal]
                max: 0
                exactMessage: menu.usedIn.menuMenuEntryAssignments