AppBundle\Entity\Main\Segment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        productCategoryAssignments:
            - Count:
                groups: [removal]
                max: 0
                exactMessage: segment.usedIn.productCategoryAssignments